### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/a-prime#30]
I started working on an a-prime conda package and quickly realized that a-prime doesn't really work that way.  Several issues an questions came up that I'd like to discuss with you all (probably first with @milenaveneziani  in person sometime early this week).

* Whereas MPAS-Analysis is truly a python package that a user interfaces with through a python driver script and a config file, A-Prime is configured by altering the driver script itself.  This means the drive script cannot be installed in a conda environment and called like other executables in the user's path.  Instead, the user needs to have some way of finding the "template" driver script so she/he can modify it.

* All of the scripts in A-Prime currently assume the current working directory is the root of the A-Prime repo, making it hard to run A-Prime when scripts are instead stored somewhere in a conda environment (e.g. in a subfolder in the bin directory).

* The path to A-Prime's various python, bash and NCL scripts are generic enough that they're not appropriate for being placed in the bin folder of a conda environment and would probably need to be placed in a path like bin/a-prime or be put in lib/a-prime or something like that.  

A user of standalone A-Prime would need a way to find the template `run_aprime.bash`, copy it to some working directory, modify it as needed and run it.  The template would then need to know where to find the rest of the A-Prime scripts in the current conda environment (something that is handled relatively seamlessly for python packages but not for scripts, which are the basis of A-Prime).

**Comment by xylar** [comment]
@doutriaux1 and @sterlingbaldwin, do you have thoughts on how A-Prime could be made a conda package and therefore incorporated into E3SM unified?  The issues in summary are:
1. Where to put the template `run_aprime.bash` within an anaconda environment so it can be found (both by the user and by @sterlingbaldwin's processflow config file)?
2. Where to put all the other scripts that are called by the driver script based on `run_aprime.bash`?

If `run_aprime.bash` could be fed with a config file rather than being altered, we could put it in `$PREFIX/bin`, where other driver scripts go.  (`$PREFIX` is the path to the anaconda environment.)  I suppose we could do that with the template, but that seems nasty since a user can't actually run that script directly even though it's in their path.  And they would need to do something like `which run_aprime.bash` to find out where to copy the template from.

I would think we could put the remaining scripts either in an `$PREFIX/bin/a-prime/bash_scripts`, etc. or `$PREFIX/lib/a-prime/bash_scripts`, etc.  Do either of you have an opinion on which is more "correct"?  These scripts can't really be run on their own so my feeling is they don't really belong in `$PREFIX/bin`

@sterlingbaldwin, out of curiosity, does your current workflow include checking out a-prime from GitHub?  If so, how much simpler would things be for you if it were part of e3sm-unified instead?

**Comment by sterlingbaldwin** [comment]
I dont check out or clone aprime from github, but instead have an aprime_code_path argument that the user has to supply. Since aprime can only work on certain machines due to its hardcoded paths, I dont see much use in making it into a conda package, its design specifically precludes any possibility of portability. 

The way the processflow works around some of aprimes issues is that I have a modified version of the run_aprime.bash file which I include as a script resource in my conda package. At run time, I swap out the bits that need to change from run to run (input paths, output paths, start and end years ect), then generate a slurm submission script that includes the "-D" argument to change the working directory to the user supplied aprime_code_path.

I dont understand why the main aprime script is written in bash, why it cant accept its parameters as command line arguments or a config file, or why it was written to only work on certain machines, but it is what it is. In my opinion all the diagnostics it runs should be incorporated into the e3sm_diags project, which would solve all these problems including the conda-package issue.

```
if [ ${HOSTNAME:0:6} == "edison" ]; then
  export machname="nersc"
elif [ ${HOSTNAME:0:4} == "rhea" ] || [ ${HOSTNAME:0:5} == "titan" ]; then
  export machname="olcf"
elif [ ${HOSTNAME:0:5} == "aims4" ]; then
  export machname="aims4"
elif [ ${HOSTNAME:0:5} == "acme1" ]; then
  export machname="acme1"
elif [ ${HOSTNAME:0:4} == "wolf" ]; then
  export machname="lanl"
elif [ ${HOSTNAME:0:6} == "blogin" ] || ([ ${HOSTNAME:0:1} == "b" ] && [[ ${HOSTNAME:1:2} =~ [0-9] ]]); then
  export machname="anvil"
elif [ ${HOSTNAME:0:5} == "theta" ]; then
  export machname="theta"
else
  echo "Unsupported host $HOSTNAME. Exiting."
  exit 1
fi
```

**Comment by xylar** [comment]
Thanks, @sterlingbaldwin. That's helpful. At this point I agree that the way forward is to incorporate the atmospheric metrics into e3sm_diags. The ocean, sea ice and land ice diagnostics are from MPAS-Analysis and should remain separate. But we should incorporate MPAS-Analysis into processflow on its own rather than through a-prime.

**Comment by milenaveneziani** [comment]
> In my opinion all the diagnostics it runs should be incorporated into the e3sm_diags project, which would solve all these problems including the conda-package issue.

From the start, a-prime was envisioned as a quick diagnostic tool to evaluate priority diagnostics for the *coupled* system. Priority metrics that people agreed would be important to look at right away when doing tuning and configuration of the coupled system. I believe @golaz and other people on the coupled group have been using this tool effectively for exactly the purpose it was designed for.
For this reason, I think removing a-prime should be a group decision.

> I dont understand why the main aprime script is written in bash, ..

That's because this was the easiest thing to do for the couple of people who were assigned with the task of creating a-prime.. :) In hindsight, and with a bit more python experience on our shoulders, I can see how things would have been easier with a python driver+config file, but that's how things went.

**Comment by golaz** [comment]
@milenaveneziani, the diagnostics from A-Prime have been very useful during the development phase of the v1 Water Cycle model. A-Prime did achieve its envisioned goal of being a quick overview diagnostic tool. Also, when needed during the "summer of ENSO", @salilmahajan was able to quickly add new targeted diagnostics to A-Prime.

Both MPAS-Analysis and E3SM Diags have evolved considerably since these early days. Therefore, we could have a discussion on how best to proceed going forward. @xylar suggestion of consolidating existing A-Prime atmosphere diagnostics with E3SM Diags and focusing on MPAS-Analysis for future ocean, sea-ice diagnostics is a possibility. Maybe the Exec committee would want to chime in on such a decision... or not.

My long term vision for E3SM, which most of us probably share, is to have a fully automated and robust post-processing environment. Configure the model, submit, and then everything else happens "magically", including any necessary processing of output files and generation of all available diagnostics.

In my short experience of running E3SM (2 1/2 years), we have made significant progress towards that goal, but we are not there yet. For example, before starting the DECK simulation campaign back in February, I evaluated the status of the processflow and concluded that it just wasn't ready for production use. So I ended up having to write my own simpler set of workflow tools. Fortunately, they worked well enough to handle the DECK simulations (1800 simulated years in 60 days) without losing my sanity, but that's not necessarily a long term solution.

**Comment by milenaveneziani** [comment]
> the diagnostics from A-Prime have been very useful during the development phase of the v1 Water Cycle model. A-Prime did achieve its envisioned goal of being a quick overview diagnostic tool. Also, when needed during the "summer of ENSO", @salilmahajan was able to quickly add new targeted diagnostics to A-Prime.

Thank you for acknowledging that, @golaz.  A lot of work went (and still goes, although more sporadically)  into making a-prime a useful package, especially considering that the people involved were not workflow people. Which is also the reason why the package is not perfect as far as workflow automation is involved.
I remember Dave was very keen on having a separate quick package for first-off evaluation of coupled simulations. Perhaps priorities have changed now, but I would just suggest to let other people weigh in on the decision to remove a-prime. I would totally be fine with it, if that is what the group prefers.

**Comment by sterlingbaldwin** [comment]
To clarify my comment a bit, aprime is very useful tool but can be a bit difficult to use. As a tool its fine, I just dont think it should be turned into a conda package. In its current form, distributing via github seems like the best approach.

The functionality of aprime is great, but its not easy for a new user to get started with it. Considering that e3sm has already invested a bunch of time and effort making a nice extensible and portable python diagnostic library in e3sm_diags, I think that eventually it would be great if the diagnostics from aprime could be incorporated as a plot-set inside e3sm_diags (I realize this would take a considerable amount of effort). For the time being, its a working tool that people are using in production (which isnt something to scoff at!), but given the amount of time and effort it would take to turn it into a portable package, the best route might be to simply not do so at all, and instead spend that effort making it part of the larger package and thus allowing more people to use it more easily. 

My current work in the processflow is trying to make it as easy to run aprime as to simply put the "aprime" argument in a config file, but if we're talking about more effort into aprime it might be worth it to think about using the (in my opinion) very nice architecture created by e3sm_diags.

**Comment by xylar** [comment]
Thanks for the feedback and discussion.  I think it makes clear that including a-prime in e3sm-unified is not the clear way forward so we should I would prefer to drop this plan.

**Comment by rljacob** [comment]
This was a good discussion.  @golaz I'd like to hear more about what you like about A-Prime.  Is it the choice of variables plotted?  The user interface?   Look and presentation of plots?  Speed?

**Comment by milenaveneziani** [comment]
Let me add that our intention is to do a final mini-release of a-prime, updating to MPAS-Analysis v1 as soon as that gets released (still waiting for a license, but that should be resolved this week), and then we can move from there.

Also, I think we should move this discussion to Confluence. I will open a discussion page there now.

**Comment by maltrud** [comment]
@rljacob, i disagree that this has been a good discussion.  it has been insulting (with the exception of @golaz ) to the developers of aprime--specifically @milenaveneziani , @xylar , @salilmahajan , and @kevans32 -- who sacrificed many of their scientific goals to provide a tool for 0th level diagnostics for the water cycle experiments.  it had to be created from scratch, including for 3 new mpas-based models for which no cesm-based tools already existed for porting.  in my opinion, they did a great job and instead of criticizing about what it lacks, they should be allowed to wrap up this phase 1 activity and rely on the workflow team to move this effort forward.

**Comment by sterlingbaldwin** [comment]
I wasnt trying to insult anyone, and apologize if my comment was taken as such. The issue is related to turning aprime into an anaconda package, and thats what I meant to address:

a) The package is written in bash, conda is built for distributing python modules.
b) The package is fundementally non-portable. This isnt an insult, its just hard coded to only work on certain machines. Conda is a distribution tool, and aprime doesnt need to be distributed since it already exists on all the supported machines. 
c) The underlying diagnostics are valuable and portable, I believe it would be worth the time and effort to organize and package them in such a way that they could be used by the wider community. Because aprime is a useful tool, it should (in my opinion, in future versions) be adapted so that it can be turned into a conda package and easily distributed.

**Comment by milenaveneziani** [comment]
> The issue is related to turning aprime into an anaconda package

I agree that various steps would be needed if a-prime were to survive in E3SM phase 2. Let's see how the discussion goes on confluence and we can plan accordingly.
